[package]
name = "sudoku_wave_function_collapse"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
clap-num = "1.1.1"
colored = "2.1.0"
rand = "0.8.5"
