

pub const CELLS_IN_ROW_PER_BOX: usize = 3;
pub const CELLS_IN_COLUMN_PER_BOX: usize = CELLS_IN_ROW_PER_BOX;
pub const BOXES_PER_ROW: usize = CELLS_IN_ROW_PER_BOX;
pub const BOXES_PER_COLUMN: usize = CELLS_IN_COLUMN_PER_BOX;
pub const DIGITS_IN_ROW_PER_CELL: usize = BOXES_PER_ROW;

pub const CERTAIN_DIGIT_ROW_IN_BOX: usize = CELLS_IN_ROW_PER_BOX / 2;

pub const DIGIT_BASE: usize = CELLS_IN_ROW_PER_BOX * BOXES_PER_ROW;

pub const ROW_COUNT: usize = DIGIT_BASE;
pub const COLUMN_COUNT: usize = ROW_COUNT;

pub const CELL_COUNT: usize = DIGIT_BASE * DIGIT_BASE;

pub const CELLS_PER_BOX: usize = CELLS_IN_ROW_PER_BOX * CELLS_IN_COLUMN_PER_BOX;
pub const CELLS_PER_ROW: usize = BOXES_PER_ROW * CELLS_IN_ROW_PER_BOX;
pub const CELLS_PER_COLUMN: usize = BOXES_PER_COLUMN * CELLS_IN_COLUMN_PER_BOX;
pub const CELLS_PER_SECTOR: usize = CELLS_PER_ROW - CELLS_IN_ROW_PER_BOX + CELLS_PER_COLUMN - CELLS_IN_COLUMN_PER_BOX + CELLS_PER_BOX;

pub const DEFAULT_HINT_COUNT: u8 = 30;


pub const TEST_BOARDS_DIR: &'static str = "test_boards";

